BEGIN TRAN



INSERT INTO Il VALUES
(1, N'Adana'),
(2, N'Adýyaman '),
(3, N'Afyon'),
(4, N'Aðrý '),
(68, N'Aksaray '),
(5, N'Amasya '),
(6, N'Ankara '),
(7, N'Antalya '),
(75, N'Ardahan '),
(8, N'Artvin'),
(9, N'Aydýn '),
(10, N'Balýkesir '),
(74, N'Bartýn '),
(72, N'Batman '),
(69, N'Bayburt '),
(11, N'Bilecik '),
(12, N'Bingöl '),
(13, N'Bitlis '),
(14, N'Bolu '),
(15, N'Burdur'),
(16, N'Bursa '),
(17, N'Çanakkale '),
(18, N'Çankýrý'),
(19, N'Çorum'),
(20, N'Denizli '),
(21, N'Diyarbakýr '),
(81, N'Düzce '),
(22, N'Edirne '),
(23, N'Elazýð'),
(24, N'Erzincan '),
(25, N'Erzurum '),
(26, N'Eskiþehir '),
(27, N'Gaziantep '),
(28, N'Giresun '),
(29, N'Gümüþhane'),
(30, N'Hakkari '),
(31, N'Hatay '),
(76, N'Iðdýr '),
(32, N'Isparta '),
(33, N'Ýçel-Mersin'),
(34, N'Ýstanbul '),
(35, N'Ýzmir '),
(78, N'Karabük'),
(70, N'Karaman '),
(36, N'Kars '),
(37, N'Kastamonu '),
(38, N'Kayseri '),
(71, N'Kýrýkkale '),
(39, N'Kýrklareli '),
(40, N'Kýrþehir '),
(79, N'Kilis '),
(41, N'Kocaeli '),
(42, N'Konya '),
(43, N'Kütahya '),
(44, N'Malatya '),
(45, N'Manisa '),
(46, N'Maraþ '),
(47, N'Mardin '),
(48, N'Muðla '),
(49, N'Muþ '),
(50, N'Nevþehir'),
(51, N'Niðde '),
(52, N'Ordu '),
(80, N'Osmaniye'),
(53, N'Rize '),
(54, N'Sakarya '),
(55, N'Samsun '),
(56, N'Siirt '),
(57, N'Sinop '),
(58, N'Sivas '),
(73, N'Þýrnak'),
(59, N'Tekirdað '),
(60, N'Tokat '),
(61, N'Trabzon '),
(62, N'Tunceli '),
(63, N'Urfa '),
(64, N'Uþak '),
(65, N'Van '),
(77, N'Yalova '),
(66, N'Yozgat '),
(67, N'Zonguldak')


SELECT * FROM Il

COMMIT TRAN

ROLLBACK TRAN