SELECT GETDATE()
SELECT DATEADD(DAY, -1*( DAY(GETDATE())-1), GETDATE())
SELECT CAST(( CAST(YEAR(GETDATE()) AS NVARCHAR(4)) + 
	'-'+
	CAST(MONTH(GETDATE()) AS NVARCHAR(2)) + 
	'-01') AS DATETIME)
	
SELECT DATEADD(SECOND, -1, DATEADD( MONTH, 1 , 
	CAST(( CAST(YEAR(GETDATE()) AS NVARCHAR(4)) + 
	'-'+
	CAST(MONTH(GETDATE()) AS NVARCHAR(2)) + 
	'-01') AS DATETIME)))